In [163]:
from transformers import Trainer

In [164]:
import pandas as pd
from pandas import read_parquet

In [168]:
from transformers import BertTokenizer, BertModel
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')
model = BertModel.from_pretrained("bert-base-multilingual-cased")

In [165]:
data_test_JA = read_parquet("../../data/japan/test-00000-of-00001.parquet")
data_test_SP = read_parquet("../../data/spain/test-00000-of-00001.parquet")
data_test_CH = read_parquet("../../data/china/test-00000-of-00001.parquet")
data_test_FR = read_parquet("../../data/france/test-00000-of-00001.parquet")
data_train_EN = read_parquet("../../data/english/train-00000-of-00001.parquet")

In [172]:
data_train_EN.iloc[1721]['tokens'].tolist()

encoded_input_wo_pad = tokenizer(data_train_EN.iloc[1721]['tokens'].tolist(), return_tensors='pt',is_split_into_words=True)
print(len(encoded_input_wo_pad.word_ids()))

Token indices sequence length is longer than the specified maximum sequence length for this model (519 > 512). Running this sequence through the model will result in indexing errors


519


In [173]:
data_train_EN

tokens  \
0      [R.H., Saunders, (, St., Lawrence, River, ), (...   
1                   [;, ', '', Anders, Lindström, '', ']   
2               [Karl, Ove, Knausgård, (, born, 1968, )]   
3                       [Atlantic, City, ,, New, Jersey]   
4      [Her, daughter, from, the, second, marriage, w...   
...                                                  ...   
19995            [Cicely, Courtneidge, ,, Ernest, Truex]   
19996                   [Aracaju, ,, Sergipe, ,, Brazil]   
19997        [Louisville, in, the, American, Civil, War]   
19998                          [16, (, David, Nugent, )]   
19999               [List, of, regional, mammals, lists]   

                                                ner_tags  \
0                      [3, 4, 0, 3, 4, 4, 0, 0, 0, 0, 0]   
1                                  [0, 0, 0, 1, 2, 0, 0]   
2                                  [1, 2, 2, 0, 0, 0, 0]   
3                                        [5, 6, 6, 6, 6]   
4      [0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, ...   
...                                                  ...   
19995                                    [1, 2, 0, 1, 2]   
19996                                    [5, 0, 5, 0, 5]   
19997                                 [5, 6, 6, 6, 6, 6]   
19998                                    [0, 0, 1, 2, 0]   
19999                                    [3, 4, 4, 4, 4]   

                                                   langs  \
0           [en, en, en, en, en, en, en, en, en, en, en]   
1                           [en, en, en, en, en, en, en]   
2                           [en, en, en, en, en, en, en]   
3                                   [en, en, en, en, en]   
4      [en, en, en, en, en, en, en, en, en, en, en, e...   
...                                                  ...   
19995                               [en, en, en, en, en]   
19996                               [en, en, en, en, en]   
19997                           [en, en, en, en, en, en]   
19998                               [en, en, en, en, en]   
19999                               [en, en, en, en, en]   

                                                   spans  
0          [ORG: R.H. Saunders, ORG: St. Lawrence River]  
1                                [PER: Anders Lindström]  
2                              [PER: Karl Ove Knausgård]  
3                      [LOC: Atlantic City , New Jersey]  
4      [PER: Marie d'Agoult, PER: Franz Liszt, PER: C...  
...                                                  ...  
19995       [PER: Cicely Courtneidge, PER: Ernest Truex]  
19996          [LOC: Aracaju, LOC: Sergipe, LOC: Brazil]  
19997        [LOC: Louisville in the American Civil War]  
19998                                [PER: David Nugent]  
19999              [ORG: List of regional mammals lists]  

[20000 rows x 4 columns]

In [111]:
text = data_test_CH.loc[0, 'tokens'].tolist()
print(text)
encoded_input_wo_pad = tokenizer(["text","ff","haha"], return_tensors='pt',is_split_into_words=True,truncation=True)
encoded_input_w_pad = tokenizer(["text","ff","haha"], return_tensors='pt',is_split_into_words=True,truncation=True,padding="max_length")
print(encoded_input_wo_pad.input_ids)
print(encoded_input_wo_pad.word_ids())


['R' 'E' 'D' 'I' 'R' 'E' 'C' 'T' '階']
tensor([[  101, 15541, 62975, 10228, 10921,   102]])
[None, 0, 1, 2, 2, None]


In [145]:
sentence_words = data_test_CH['tokens'][0].tolist()
print(sentence_words)
tokenized_words= tokenizer(sentence_words, return_tensors='pt',is_split_into_words=True,truncation=True)
print(tokenized_words)
print(tokenized_words.word_ids())

['R', 'E', 'D', 'I', 'R', 'E', 'C', 'T', '階']
{'input_ids': tensor([[ 101,  155,  142,  141,  146,  155,  142,  140,  157, 8244,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, None]


In [130]:
print(encoded_input_w_pad.token_type_ids)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0

In [146]:
output_wo_pad = model(**encoded_input_wo_pad)
output_w_pad = model(**encoded_input_w_pad)
print(output_wo_pad.last_hidden_state.shape)

torch.Size([1, 6, 768])


In [114]:
out_without_pad=output_wo_pad.last_hidden_state[0][2]
out_with_pad=output_w_pad.last_hidden_state[0][2]

In [125]:
out_with_pad

tensor([-9.4939e-02, -3.7332e-01,  1.4714e+00, -2.6651e-01,  6.9432e-01,
        -8.0943e-01, -2.1733e-01, -5.4869e-01,  1.9661e-03,  5.6555e-02,
         1.1869e+00, -2.8952e-01,  8.2650e-01,  1.6497e-01, -9.9516e-02,
        -2.0574e-01,  3.9803e-01,  2.0877e-01, -5.1269e-01,  8.0204e-01,
         1.3882e-02, -6.5385e-01,  1.9936e-01, -2.8387e-01, -1.1863e-01,
         3.8612e-01, -6.1916e-01, -9.9126e-02, -4.2922e-01,  1.5927e-01,
        -1.1547e-01,  8.1942e-02,  3.1755e-01,  9.3555e-01, -3.3490e-01,
         9.7190e-01, -4.2060e-01,  3.0454e-01,  5.9740e-01, -6.7126e-01,
        -3.8884e-02,  1.8366e-01, -6.3722e-02,  5.1242e-01,  5.7403e-01,
        -9.4466e-01,  1.3993e-01,  1.3399e-01, -1.1592e+00, -1.5897e-01,
        -6.7248e-02, -4.6495e-01,  4.0441e-01,  4.9651e-01, -7.1324e-02,
         3.9922e-01,  8.6699e-01, -4.6315e-01, -3.1390e-01,  8.2018e-02,
         6.9478e-01,  4.9652e-01, -1.7075e-01,  1.9144e-01, -8.3377e-01,
        -2.8030e-01,  3.3190e-01,  7.6397e-01,  7.6

In [121]:
import torch
print(out_with_pad == out_without_pad)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [89]:
print(output.last_hidden_state.shape)
print(output.pooler_output.shape)

torch.Size([1, 512, 768])
torch.Size([1, 768])
